## Cientista de Dados Python para Iniciantes

In [ ]:
# importando as bibliotecas necessárias
import numpy as np 
import sys

# Criando sua primeiro Array

In [9]:
a = [1,2,3,4,5]
b = np.array([1,2,3,4,5])

In [3]:
print(a)
print(b)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [5]:
sys.getsizeof(a)

120

In [6]:
b.nbytes

20

# Criando Arrays em 1D, 2D e 3D

In [11]:
# Arry 1D

d1 = np.array([1,2,3])
print(d1)

[1 2 3]


In [12]:
d1.shape

(3,)

In [13]:
d1.ndim

1

In [14]:
d1.dtype

dtype('int32')

In [3]:
# Arry 2D
d2 = np.array([[1,2,3],[4,5,6]])
print(d2)

[[1 2 3]
 [4 5 6]]


In [4]:
d2.shape

(2, 3)

In [5]:
d2.ndim

2

In [6]:
d2.dtype

dtype('int32')

In [12]:
# Arry 3D
d3 = np.array([[[1,2],[3,4]], [[5,6], [7,8]]] )
print(d3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
d3.shape

(2, 2, 2)

In [14]:
d3.ndim

3

In [15]:
d3.dtype

dtype('int32')

# Somando duas Arrays

In [16]:
a = np.array([2,3,4])
b = np.array([2,3,4])

In [19]:
result =np.add(a, b)
print(result)

[4 6 8]


# Selecionando itens em Arrays

In [30]:
a = np.array([[2,3,'R$19,90',5], [6,7,'Apple',9]])
print(a)

[['2' '3' 'R$19,90' '5']
 ['6' '7' 'Apple' '9']]


In [29]:
# array [linha, coluna]

a [1,2]

'Apple'

In [23]:
a [1,3]

9

In [24]:
a [0,0]

2

In [25]:
a [1,-2]

8

In [26]:
a[0,:]

array([2, 3, 4, 5])

In [31]:
a[:,2]

array(['R$19,90', 'Apple'], dtype='<U11')